/* Automatically generated by Amaranth 0.3. Do not edit. */
/* Generated by Yosys 0.13+3 (git sha1 61324cf55, clang 10.0.0-4ubuntu1 -fPIC -Os) */

(* \amaranth.hierarchy  = "top.tb.dut.delayer" *)
(* generator = "Amaranth" *)
module delayer(sync_1e6_rst, start, done, counter_out, sync_1e6_clk);
  reg \$auto$verilog_backend.cc:2083:dump_module$49  = 0;
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/forks/gateware/examples/amlib/amlib/utils/timer.py:21" *)
  wire \$1 ;
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/forks/gateware/examples/amlib/amlib/utils/timer.py:37" *)
  wire [32:0] \$10 ;
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/forks/gateware/examples/amlib/amlib/utils/timer.py:37" *)
  wire [32:0] \$11 ;
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/forks/gateware/examples/amlib/amlib/utils/timer.py:42" *)
  wire \$13 ;
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/forks/gateware/examples/amlib/amlib/utils/timer.py:45" *)
  wire [32:0] \$15 ;
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/forks/gateware/examples/amlib/amlib/utils/timer.py:45" *)
  wire [32:0] \$16 ;
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/forks/gateware/examples/amlib/amlib/utils/timer.py:30" *)
  wire \$18 ;
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/forks/gateware/examples/amlib/amlib/utils/timer.py:30" *)
  wire \$20 ;
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/forks/gateware/examples/amlib/amlib/utils/timer.py:38" *)
  wire \$22 ;
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/forks/gateware/examples/amlib/amlib/utils/timer.py:42" *)
  wire \$24 ;
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/forks/gateware/examples/amlib/amlib/utils/timer.py:30" *)
  wire \$3 ;
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/forks/gateware/examples/amlib/amlib/utils/timer.py:30" *)
  wire \$5 ;
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/forks/gateware/examples/amlib/amlib/utils/timer.py:33" *)
  wire [32:0] \$7 ;
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/forks/gateware/examples/amlib/amlib/utils/timer.py:33" *)
  wire [32:0] \$8 ;
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/forks/gateware/examples/amlib/amlib/utils/timer.py:11" *)
  output [31:0] counter_out;
  reg [31:0] counter_out = 32'd0;
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/forks/gateware/examples/amlib/amlib/utils/timer.py:11" *)
  reg [31:0] \counter_out$next ;
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/forks/gateware/examples/amlib/amlib/utils/timer.py:13" *)
  output done;
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/forks/gateware/examples/amlib/amlib/utils/timer.py:20" *)
  reg [1:0] fsm_state = 2'h1;
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/forks/gateware/examples/amlib/amlib/utils/timer.py:20" *)
  reg [1:0] \fsm_state$next ;
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/forks/gateware/examples/amlib/amlib/utils/timer.py:10" *)
  wire [31:0] reload;
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/forks/gateware/examples/amlib/amlib/utils/timer.py:12" *)
  input start;
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/gateware/amtest/amtest/boards/ulx3s/common/clks.py:26" *)
  input sync_1e6_clk;
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/gateware/amtest/amtest/boards/ulx3s/common/clks.py:26" *)
  input sync_1e6_rst;
  assign \$11  = counter_out - (* src = "/home/ubuntu/from_host/x/Documents/git_repos/forks/gateware/examples/amlib/amlib/utils/timer.py:37" *) 1'h1;
  assign \$18  = counter_out > (* src = "/home/ubuntu/from_host/x/Documents/git_repos/forks/gateware/examples/amlib/amlib/utils/timer.py:30" *) 1'h0;
  assign \$1  = ! (* src = "/home/ubuntu/from_host/x/Documents/git_repos/forks/gateware/examples/amlib/amlib/utils/timer.py:21" *) fsm_state;
  assign \$20  = start & (* src = "/home/ubuntu/from_host/x/Documents/git_repos/forks/gateware/examples/amlib/amlib/utils/timer.py:30" *) \$18 ;
  assign \$22  = counter_out == (* src = "/home/ubuntu/from_host/x/Documents/git_repos/forks/gateware/examples/amlib/amlib/utils/timer.py:38" *) 1'h1;
  assign \$3  = counter_out > (* src = "/home/ubuntu/from_host/x/Documents/git_repos/forks/gateware/examples/amlib/amlib/utils/timer.py:30" *) 1'h0;
  assign \$5  = start & (* src = "/home/ubuntu/from_host/x/Documents/git_repos/forks/gateware/examples/amlib/amlib/utils/timer.py:30" *) \$3 ;
  assign \$8  = counter_out - (* src = "/home/ubuntu/from_host/x/Documents/git_repos/forks/gateware/examples/amlib/amlib/utils/timer.py:33" *) 1'h1;
  always @(posedge sync_1e6_clk)
    fsm_state <= \fsm_state$next ;
  always @(posedge sync_1e6_clk)
    counter_out <= \counter_out$next ;
  always @* begin
    if (\$auto$verilog_backend.cc:2083:dump_module$49 ) begin end
    \counter_out$next  = counter_out;
    (* src = "/home/ubuntu/from_host/x/Documents/git_repos/forks/gateware/examples/amlib/amlib/utils/timer.py:20" *)
    casez (fsm_state)
      /* \amaranth.decoding  = "IDLE/1" */
      /* src = "/home/ubuntu/from_host/x/Documents/git_repos/forks/gateware/examples/amlib/amlib/utils/timer.py:23" */
      2'h1:
        begin
          \counter_out$next  = 32'd1000000;
          (* src = "/home/ubuntu/from_host/x/Documents/git_repos/forks/gateware/examples/amlib/amlib/utils/timer.py:30" *)
          casez (\$5 )
            /* src = "/home/ubuntu/from_host/x/Documents/git_repos/forks/gateware/examples/amlib/amlib/utils/timer.py:30" */
            1'h1:
                \counter_out$next  = \$8 [31:0];
          endcase
        end
      /* \amaranth.decoding  = "RUNNING/2" */
      /* src = "/home/ubuntu/from_host/x/Documents/git_repos/forks/gateware/examples/amlib/amlib/utils/timer.py:36" */
      2'h2:
          \counter_out$next  = \$11 [31:0];
      /* \amaranth.decoding  = "DONE/0" */
      /* src = "/home/ubuntu/from_host/x/Documents/git_repos/forks/gateware/examples/amlib/amlib/utils/timer.py:41" */
      2'h0:
          (* src = "/home/ubuntu/from_host/x/Documents/git_repos/forks/gateware/examples/amlib/amlib/utils/timer.py:42" *)
          casez (\$13 )
            /* src = "/home/ubuntu/from_host/x/Documents/git_repos/forks/gateware/examples/amlib/amlib/utils/timer.py:42" */
            1'h1:
                \counter_out$next  = \$16 [31:0];
          endcase
    endcase
    (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/xfrm.py:519" *)
    casez (sync_1e6_rst)
      1'h1:
          \counter_out$next  = 32'd0;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2083:dump_module$49 ) begin end
    \fsm_state$next  = fsm_state;
    (* src = "/home/ubuntu/from_host/x/Documents/git_repos/forks/gateware/examples/amlib/amlib/utils/timer.py:20" *)
    casez (fsm_state)
      /* \amaranth.decoding  = "IDLE/1" */
      /* src = "/home/ubuntu/from_host/x/Documents/git_repos/forks/gateware/examples/amlib/amlib/utils/timer.py:23" */
      2'h1:
          (* src = "/home/ubuntu/from_host/x/Documents/git_repos/forks/gateware/examples/amlib/amlib/utils/timer.py:30" *)
          casez (\$20 )
            /* src = "/home/ubuntu/from_host/x/Documents/git_repos/forks/gateware/examples/amlib/amlib/utils/timer.py:30" */
            1'h1:
                \fsm_state$next  = 2'h2;
          endcase
      /* \amaranth.decoding  = "RUNNING/2" */
      /* src = "/home/ubuntu/from_host/x/Documents/git_repos/forks/gateware/examples/amlib/amlib/utils/timer.py:36" */
      2'h2:
          (* src = "/home/ubuntu/from_host/x/Documents/git_repos/forks/gateware/examples/amlib/amlib/utils/timer.py:38" *)
          casez (\$22 )
            /* src = "/home/ubuntu/from_host/x/Documents/git_repos/forks/gateware/examples/amlib/amlib/utils/timer.py:38" */
            1'h1:
                \fsm_state$next  = 2'h0;
          endcase
      /* \amaranth.decoding  = "DONE/0" */
      /* src = "/home/ubuntu/from_host/x/Documents/git_repos/forks/gateware/examples/amlib/amlib/utils/timer.py:41" */
      2'h0:
          (* full_case = 32'd1 *)
          (* src = "/home/ubuntu/from_host/x/Documents/git_repos/forks/gateware/examples/amlib/amlib/utils/timer.py:42" *)
          casez (\$24 )
            /* src = "/home/ubuntu/from_host/x/Documents/git_repos/forks/gateware/examples/amlib/amlib/utils/timer.py:42" */
            1'h1:
                \fsm_state$next  = 2'h2;
            /* src = "/home/ubuntu/from_host/x/Documents/git_repos/forks/gateware/examples/amlib/amlib/utils/timer.py:48" */
            default:
                \fsm_state$next  = 2'h1;
          endcase
    endcase
    (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/xfrm.py:519" *)
    casez (sync_1e6_rst)
      1'h1:
          \fsm_state$next  = 2'h1;
    endcase
  end
  assign \$7  = \$8 ;
  assign \$10  = \$11 ;
  assign \$15  = \$16 ;
  assign reload = 32'd0;
  assign done = \$1 ;
  assign \$13  = 1'h0;
  assign \$16  = 33'h1ffffffff;
  assign \$24  = 1'h0;
endmodule

(* \amaranth.hierarchy  = "top.tb.dut" *)
(* generator = "Amaranth" *)
module dut(sync_1e6_rst, ui__start, ui__done, ui__active, debug__count, sync_1e6_clk);
  reg \$auto$verilog_backend.cc:2083:dump_module$50  = 0;
  (* src = "tests2_feb2022/test1_amlib_timers.py:67" *)
  wire \$5 ;
  (* src = "tests2_feb2022/test1_amlib_timers.py:48" *)
  output [31:0] debug__count;
  reg [31:0] debug__count = 32'd0;
  (* src = "tests2_feb2022/test1_amlib_timers.py:55" *)
  reg [31:0] \debug__count$4  = 32'd0;
  (* src = "tests2_feb2022/test1_amlib_timers.py:55" *)
  reg [31:0] \debug__count$4$next ;
  (* src = "tests2_feb2022/test1_amlib_timers.py:48" *)
  reg [31:0] \debug__count$next ;
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/forks/gateware/examples/amlib/amlib/utils/timer.py:11" *)
  wire [31:0] delayer_counter_out;
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/forks/gateware/examples/amlib/amlib/utils/timer.py:13" *)
  wire delayer_done;
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/forks/gateware/examples/amlib/amlib/utils/timer.py:12" *)
  reg delayer_start = 1'h0;
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/forks/gateware/examples/amlib/amlib/utils/timer.py:12" *)
  reg \delayer_start$next ;
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/gateware/amtest/amtest/boards/ulx3s/common/clks.py:26" *)
  input sync_1e6_clk;
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/gateware/amtest/amtest/boards/ulx3s/common/clks.py:26" *)
  input sync_1e6_rst;
  (* src = "tests2_feb2022/test1_amlib_timers.py:47" *)
  output ui__active;
  reg ui__active = 1'h0;
  (* src = "tests2_feb2022/test1_amlib_timers.py:54" *)
  reg \ui__active$3  = 1'h0;
  (* src = "tests2_feb2022/test1_amlib_timers.py:54" *)
  reg \ui__active$3$next ;
  (* src = "tests2_feb2022/test1_amlib_timers.py:47" *)
  reg \ui__active$next ;
  (* src = "tests2_feb2022/test1_amlib_timers.py:47" *)
  output ui__done;
  reg ui__done = 1'h0;
  (* src = "tests2_feb2022/test1_amlib_timers.py:54" *)
  reg \ui__done$2  = 1'h0;
  (* src = "tests2_feb2022/test1_amlib_timers.py:54" *)
  reg \ui__done$2$next ;
  (* src = "tests2_feb2022/test1_amlib_timers.py:47" *)
  reg \ui__done$next ;
  (* src = "tests2_feb2022/test1_amlib_timers.py:47" *)
  input ui__start;
  (* src = "tests2_feb2022/test1_amlib_timers.py:54" *)
  reg \ui__start$1  = 1'h0;
  (* src = "tests2_feb2022/test1_amlib_timers.py:54" *)
  reg \ui__start$1$next ;
  assign \$5  = delayer_counter_out != (* src = "tests2_feb2022/test1_amlib_timers.py:67" *) 20'hf4240;
  always @(posedge sync_1e6_clk)
    \ui__active$3  <= \ui__active$3$next ;
  always @(posedge sync_1e6_clk)
    \debug__count$4  <= \debug__count$4$next ;
  always @(posedge sync_1e6_clk)
    \ui__done$2  <= \ui__done$2$next ;
  always @(posedge sync_1e6_clk)
    delayer_start <= \delayer_start$next ;
  always @(posedge sync_1e6_clk)
    debug__count <= \debug__count$next ;
  always @(posedge sync_1e6_clk)
    ui__active <= \ui__active$next ;
  always @(posedge sync_1e6_clk)
    ui__done <= \ui__done$next ;
  always @(posedge sync_1e6_clk)
    \ui__start$1  <= \ui__start$1$next ;
  delayer delayer (
    .counter_out(delayer_counter_out),
    .done(delayer_done),
    .start(delayer_start),
    .sync_1e6_clk(sync_1e6_clk),
    .sync_1e6_rst(sync_1e6_rst)
  );
  always @* begin
    if (\$auto$verilog_backend.cc:2083:dump_module$50 ) begin end
    \ui__start$1$next  = ui__start;
    (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/xfrm.py:519" *)
    casez (sync_1e6_rst)
      1'h1:
          \ui__start$1$next  = 1'h0;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2083:dump_module$50 ) begin end
    \ui__done$next  = \ui__done$2 ;
    (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/xfrm.py:519" *)
    casez (sync_1e6_rst)
      1'h1:
          \ui__done$next  = 1'h0;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2083:dump_module$50 ) begin end
    \ui__active$next  = \ui__active$3 ;
    (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/xfrm.py:519" *)
    casez (sync_1e6_rst)
      1'h1:
          \ui__active$next  = 1'h0;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2083:dump_module$50 ) begin end
    \debug__count$next  = \debug__count$4 ;
    (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/xfrm.py:519" *)
    casez (sync_1e6_rst)
      1'h1:
          \debug__count$next  = 32'd0;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2083:dump_module$50 ) begin end
    \delayer_start$next  = \ui__start$1 ;
    (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/xfrm.py:519" *)
    casez (sync_1e6_rst)
      1'h1:
          \delayer_start$next  = 1'h0;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2083:dump_module$50 ) begin end
    \ui__done$2$next  = delayer_done;
    (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/xfrm.py:519" *)
    casez (sync_1e6_rst)
      1'h1:
          \ui__done$2$next  = 1'h0;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2083:dump_module$50 ) begin end
    \debug__count$4$next  = delayer_counter_out;
    (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/xfrm.py:519" *)
    casez (sync_1e6_rst)
      1'h1:
          \debug__count$4$next  = 32'd0;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2083:dump_module$50 ) begin end
    \ui__active$3$next  = \$5 ;
    (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/xfrm.py:519" *)
    casez (sync_1e6_rst)
      1'h1:
          \ui__active$3$next  = 1'h0;
    endcase
  end
endmodule

(* \amaranth.hierarchy  = "top.i_button_ffsync" *)
(* generator = "Amaranth" *)
module i_button_ffsync(i_unsync_buttons__pwr, i_unsync_buttons__fireA, i_unsync_buttons__fireB, i_unsync_buttons__up, i_unsync_buttons__down, i_unsync_buttons__left, i_unsync_buttons__right, i_buttons__pwr, i_buttons__right, i_buttons__left, rst, clk);
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/gateware/amtest/amtest/boards/ulx3s/common/clks.py:40" *)
  input clk;
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/gateware/amtest/amtest/boards/ulx3s/common/upload.py:85" *)
  wire i_buttons__down;
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/gateware/amtest/amtest/boards/ulx3s/common/upload.py:85" *)
  wire i_buttons__fireA;
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/gateware/amtest/amtest/boards/ulx3s/common/upload.py:85" *)
  wire i_buttons__fireB;
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/gateware/amtest/amtest/boards/ulx3s/common/upload.py:85" *)
  output i_buttons__left;
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/gateware/amtest/amtest/boards/ulx3s/common/upload.py:85" *)
  output i_buttons__pwr;
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/gateware/amtest/amtest/boards/ulx3s/common/upload.py:85" *)
  output i_buttons__right;
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/gateware/amtest/amtest/boards/ulx3s/common/upload.py:85" *)
  wire i_buttons__up;
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/gateware/amtest/amtest/boards/ulx3s/common/upload.py:61" *)
  input i_unsync_buttons__down;
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/gateware/amtest/amtest/boards/ulx3s/common/upload.py:61" *)
  input i_unsync_buttons__fireA;
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/gateware/amtest/amtest/boards/ulx3s/common/upload.py:61" *)
  input i_unsync_buttons__fireB;
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/gateware/amtest/amtest/boards/ulx3s/common/upload.py:61" *)
  input i_unsync_buttons__left;
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/gateware/amtest/amtest/boards/ulx3s/common/upload.py:61" *)
  input i_unsync_buttons__pwr;
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/gateware/amtest/amtest/boards/ulx3s/common/upload.py:61" *)
  input i_unsync_buttons__right;
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/gateware/amtest/amtest/boards/ulx3s/common/upload.py:61" *)
  input i_unsync_buttons__up;
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/gateware/amtest/amtest/boards/ulx3s/common/clks.py:40" *)
  input rst;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/lib/cdc.py:89" *)
  reg [6:0] stage0 = 7'h00;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/lib/cdc.py:89" *)
  wire [6:0] \stage0$next ;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/lib/cdc.py:89" *)
  reg [6:0] stage1 = 7'h00;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/lib/cdc.py:89" *)
  wire [6:0] \stage1$next ;
  always @(posedge clk)
    stage1 <= stage0;
  always @(posedge clk)
    stage0 <= { i_unsync_buttons__right, i_unsync_buttons__left, i_unsync_buttons__down, i_unsync_buttons__up, i_unsync_buttons__fireB, i_unsync_buttons__fireA, i_unsync_buttons__pwr };
  assign { i_buttons__right, i_buttons__left, i_buttons__down, i_buttons__up, i_buttons__fireB, i_buttons__fireA, i_buttons__pwr } = stage1;
  assign \stage1$next  = stage0;
  assign \stage0$next  = { i_unsync_buttons__right, i_unsync_buttons__left, i_unsync_buttons__down, i_unsync_buttons__up, i_unsync_buttons__fireB, i_unsync_buttons__fireA, i_unsync_buttons__pwr };
endmodule

(* \amaranth.hierarchy  = "top.pin_button_down_0" *)
(* generator = "Amaranth" *)
module pin_button_down_0(button_down_0__io, button_down_0__i);
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  output button_down_0__i;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  input button_down_0__io;
  IB button_down_0_0 (
    .I(button_down_0__io),
    .O(button_down_0__i)
  );
endmodule

(* \amaranth.hierarchy  = "top.pin_button_fire_0" *)
(* generator = "Amaranth" *)
module pin_button_fire_0(button_fire_0__io, button_fire_0__i);
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  output button_fire_0__i;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  input button_fire_0__io;
  IB button_fire_0_0 (
    .I(button_fire_0__io),
    .O(button_fire_0__i)
  );
endmodule

(* \amaranth.hierarchy  = "top.pin_button_fire_1" *)
(* generator = "Amaranth" *)
module pin_button_fire_1(button_fire_1__io, button_fire_1__i);
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  output button_fire_1__i;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  input button_fire_1__io;
  IB button_fire_1_0 (
    .I(button_fire_1__io),
    .O(button_fire_1__i)
  );
endmodule

(* \amaranth.hierarchy  = "top.pin_button_left_0" *)
(* generator = "Amaranth" *)
module pin_button_left_0(button_left_0__io, button_left_0__i);
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  output button_left_0__i;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  input button_left_0__io;
  IB button_left_0_0 (
    .I(button_left_0__io),
    .O(button_left_0__i)
  );
endmodule

(* \amaranth.hierarchy  = "top.pin_button_pwr_0" *)
(* generator = "Amaranth" *)
module pin_button_pwr_0(button_pwr_0__io, button_pwr_0__i);
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/vendor/lattice_ecp5.py:465" *)
  wire \$1 ;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  output button_pwr_0__i;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/vendor/lattice_ecp5.py:464" *)
  wire button_pwr_0__i_n;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  input button_pwr_0__io;
  assign \$1  = ~ (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/vendor/lattice_ecp5.py:465" *) button_pwr_0__i_n;
  IB button_pwr_0_0 (
    .I(button_pwr_0__io),
    .O(button_pwr_0__i_n)
  );
  assign button_pwr_0__i = \$1 ;
endmodule

(* \amaranth.hierarchy  = "top.pin_button_right_0" *)
(* generator = "Amaranth" *)
module pin_button_right_0(button_right_0__io, button_right_0__i);
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  output button_right_0__i;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  input button_right_0__io;
  IB button_right_0_0 (
    .I(button_right_0__io),
    .O(button_right_0__i)
  );
endmodule

(* \amaranth.hierarchy  = "top.pin_button_up_0" *)
(* generator = "Amaranth" *)
module pin_button_up_0(button_up_0__io, button_up_0__i);
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  output button_up_0__i;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  input button_up_0__io;
  IB button_up_0_0 (
    .I(button_up_0__io),
    .O(button_up_0__i)
  );
endmodule

(* \amaranth.hierarchy  = "top.pin_clk25_0" *)
(* generator = "Amaranth" *)
module pin_clk25_0(clk25_0__io, clk25_0__i);
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  output clk25_0__i;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  input clk25_0__io;
  IB clk25_0_0 (
    .I(clk25_0__io),
    .O(clk25_0__i)
  );
endmodule

(* \amaranth.hierarchy  = "top.pin_esp32_spi_0__en" *)
(* generator = "Amaranth" *)
module pin_esp32_spi_0__en(esp32_spi_0__en__io, esp32_spi_0__en__o);
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  output esp32_spi_0__en__io;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  input esp32_spi_0__en__o;
  OB esp32_spi_0__en_0 (
    .I(esp32_spi_0__en__o),
    .O(esp32_spi_0__en__io)
  );
endmodule

(* \amaranth.hierarchy  = "top.pin_esp32_spi_0__gpio0" *)
(* generator = "Amaranth" *)
module pin_esp32_spi_0__gpio0(esp32_spi_0__gpio0__io, esp32_spi_0__gpio0__o);
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/vendor/lattice_ecp5.py:531" *)
  wire \$1 ;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  wire esp32_spi_0__gpio0__i;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  inout esp32_spi_0__gpio0__io;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  input esp32_spi_0__gpio0__o;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  wire esp32_spi_0__gpio0__oe;
  BB esp32_spi_0__gpio0_0 (
    .B(esp32_spi_0__gpio0__io),
    .I(esp32_spi_0__gpio0__o),
    .O(esp32_spi_0__gpio0__i),
    .T(1'h1)
  );
  assign esp32_spi_0__gpio0__oe = 1'h0;
  assign \$1  = 1'h1;
endmodule

(* \amaranth.hierarchy  = "top.pin_esp32_spi_0__gpio12_cipo" *)
(* generator = "Amaranth" *)
module pin_esp32_spi_0__gpio12_cipo(esp32_spi_0__gpio12_cipo__io);
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  output esp32_spi_0__gpio12_cipo__io;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  wire esp32_spi_0__gpio12_cipo__o;
  OB esp32_spi_0__gpio12_cipo_0 (
    .I(1'h0),
    .O(esp32_spi_0__gpio12_cipo__io)
  );
  assign esp32_spi_0__gpio12_cipo__o = 1'h0;
endmodule

(* \amaranth.hierarchy  = "top.pin_esp32_spi_0__gpio16_sclk" *)
(* generator = "Amaranth" *)
module pin_esp32_spi_0__gpio16_sclk(esp32_spi_0__gpio16_sclk__io);
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  wire esp32_spi_0__gpio16_sclk__i;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  input esp32_spi_0__gpio16_sclk__io;
  IB esp32_spi_0__gpio16_sclk_0 (
    .I(esp32_spi_0__gpio16_sclk__io),
    .O(esp32_spi_0__gpio16_sclk__i)
  );
endmodule

(* \amaranth.hierarchy  = "top.pin_esp32_spi_0__gpio4_copi" *)
(* generator = "Amaranth" *)
module pin_esp32_spi_0__gpio4_copi(esp32_spi_0__gpio4_copi__io);
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  wire esp32_spi_0__gpio4_copi__i;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  input esp32_spi_0__gpio4_copi__io;
  IB esp32_spi_0__gpio4_copi_0 (
    .I(esp32_spi_0__gpio4_copi__io),
    .O(esp32_spi_0__gpio4_copi__i)
  );
endmodule

(* \amaranth.hierarchy  = "top.pin_esp32_spi_0__gpio5_cs" *)
(* generator = "Amaranth" *)
module pin_esp32_spi_0__gpio5_cs(esp32_spi_0__gpio5_cs__io);
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/vendor/lattice_ecp5.py:465" *)
  wire \$1 ;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  wire esp32_spi_0__gpio5_cs__i;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/vendor/lattice_ecp5.py:464" *)
  wire esp32_spi_0__gpio5_cs__i_n;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  input esp32_spi_0__gpio5_cs__io;
  assign \$1  = ~ (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/vendor/lattice_ecp5.py:465" *) esp32_spi_0__gpio5_cs__i_n;
  IB esp32_spi_0__gpio5_cs_0 (
    .I(esp32_spi_0__gpio5_cs__io),
    .O(esp32_spi_0__gpio5_cs__i_n)
  );
  assign esp32_spi_0__gpio5_cs__i = \$1 ;
endmodule

(* \amaranth.hierarchy  = "top.pin_esp32_spi_0__rx" *)
(* generator = "Amaranth" *)
module pin_esp32_spi_0__rx(esp32_spi_0__rx__io, esp32_spi_0__rx__i);
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  output esp32_spi_0__rx__i;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  input esp32_spi_0__rx__io;
  IB esp32_spi_0__rx_0 (
    .I(esp32_spi_0__rx__io),
    .O(esp32_spi_0__rx__i)
  );
endmodule

(* \amaranth.hierarchy  = "top.pin_esp32_spi_0__tx" *)
(* generator = "Amaranth" *)
module pin_esp32_spi_0__tx(esp32_spi_0__tx__io, esp32_spi_0__tx__o);
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  output esp32_spi_0__tx__io;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  input esp32_spi_0__tx__o;
  OB esp32_spi_0__tx_0 (
    .I(esp32_spi_0__tx__o),
    .O(esp32_spi_0__tx__io)
  );
endmodule

(* \amaranth.hierarchy  = "top.pin_led_0" *)
(* generator = "Amaranth" *)
module pin_led_0(led_0__io, led_0__o);
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  output led_0__io;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  input led_0__o;
  OB led_0_0 (
    .I(led_0__o),
    .O(led_0__io)
  );
endmodule

(* \amaranth.hierarchy  = "top.pin_led_1" *)
(* generator = "Amaranth" *)
module pin_led_1(led_1__io, led_1__o);
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  output led_1__io;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  input led_1__o;
  OB led_1_0 (
    .I(led_1__o),
    .O(led_1__io)
  );
endmodule

(* \amaranth.hierarchy  = "top.pin_led_2" *)
(* generator = "Amaranth" *)
module pin_led_2(led_2__io, led_2__o);
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  output led_2__io;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  input led_2__o;
  OB led_2_0 (
    .I(led_2__o),
    .O(led_2__io)
  );
endmodule

(* \amaranth.hierarchy  = "top.pin_led_3" *)
(* generator = "Amaranth" *)
module pin_led_3(led_3__io, led_3__o);
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  output led_3__io;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  input led_3__o;
  OB led_3_0 (
    .I(led_3__o),
    .O(led_3__io)
  );
endmodule

(* \amaranth.hierarchy  = "top.pin_led_4" *)
(* generator = "Amaranth" *)
module pin_led_4(led_4__io, led_4__o);
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  output led_4__io;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  input led_4__o;
  OB led_4_0 (
    .I(led_4__o),
    .O(led_4__io)
  );
endmodule

(* \amaranth.hierarchy  = "top.pin_led_5" *)
(* generator = "Amaranth" *)
module pin_led_5(led_5__io, led_5__o);
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  output led_5__io;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  input led_5__o;
  OB led_5_0 (
    .I(led_5__o),
    .O(led_5__io)
  );
endmodule

(* \amaranth.hierarchy  = "top.pin_led_6" *)
(* generator = "Amaranth" *)
module pin_led_6(led_6__io, led_6__o);
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  output led_6__io;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  input led_6__o;
  OB led_6_0 (
    .I(led_6__o),
    .O(led_6__io)
  );
endmodule

(* \amaranth.hierarchy  = "top.pin_led_7" *)
(* generator = "Amaranth" *)
module pin_led_7(led_7__io, led_7__o);
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  output led_7__io;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  input led_7__o;
  OB led_7_0 (
    .I(led_7__o),
    .O(led_7__io)
  );
endmodule

(* \amaranth.hierarchy  = "top.pin_uart_0__dtr" *)
(* generator = "Amaranth" *)
module pin_uart_0__dtr(uart_0__dtr__io, uart_0__dtr__i);
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  output uart_0__dtr__i;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  input uart_0__dtr__io;
  IB uart_0__dtr_0 (
    .I(uart_0__dtr__io),
    .O(uart_0__dtr__i)
  );
endmodule

(* \amaranth.hierarchy  = "top.pin_uart_0__rts" *)
(* generator = "Amaranth" *)
module pin_uart_0__rts(uart_0__rts__io, uart_0__rts__i);
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  output uart_0__rts__i;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  input uart_0__rts__io;
  IB uart_0__rts_0 (
    .I(uart_0__rts__io),
    .O(uart_0__rts__i)
  );
endmodule

(* \amaranth.hierarchy  = "top.pin_uart_0__rx" *)
(* generator = "Amaranth" *)
module pin_uart_0__rx(uart_0__rx__io, uart_0__rx__i);
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  output uart_0__rx__i;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  input uart_0__rx__io;
  IB uart_0__rx_0 (
    .I(uart_0__rx__io),
    .O(uart_0__rx__i)
  );
endmodule

(* \amaranth.hierarchy  = "top.pin_uart_0__tx" *)
(* generator = "Amaranth" *)
module pin_uart_0__tx(uart_0__tx__io, uart_0__tx__o);
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  output uart_0__tx__io;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  input uart_0__tx__o;
  OB uart_0__tx_0 (
    .I(uart_0__tx__o),
    .O(uart_0__tx__io)
  );
endmodule

(* \amaranth.hierarchy  = "top.tb" *)
(* generator = "Amaranth" *)
module tb(ui__start, ui__done, ui__active, sync_1e6_rst, leds, sync_1e6_clk);
  reg \$auto$verilog_backend.cc:2083:dump_module$51  = 0;
  (* src = "tests2_feb2022/test1_amlib_timers.py:97" *)
  reg [31:0] debug__count = 32'd0;
  (* src = "tests2_feb2022/test1_amlib_timers.py:97" *)
  reg [31:0] \debug__count$next ;
  (* src = "tests2_feb2022/test1_amlib_timers.py:48" *)
  wire [31:0] dut_debug__count;
  (* src = "tests2_feb2022/test1_amlib_timers.py:47" *)
  wire dut_ui__active;
  (* src = "tests2_feb2022/test1_amlib_timers.py:47" *)
  wire dut_ui__done;
  (* src = "tests2_feb2022/test1_amlib_timers.py:47" *)
  reg dut_ui__start = 1'h0;
  (* src = "tests2_feb2022/test1_amlib_timers.py:47" *)
  reg \dut_ui__start$next ;
  (* src = "tests2_feb2022/test1_amlib_timers.py:89" *)
  output [7:0] leds;
  reg [7:0] leds = 8'h00;
  (* src = "tests2_feb2022/test1_amlib_timers.py:89" *)
  wire [7:0] \leds$next ;
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/gateware/amtest/amtest/boards/ulx3s/common/clks.py:26" *)
  input sync_1e6_clk;
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/gateware/amtest/amtest/boards/ulx3s/common/clks.py:26" *)
  input sync_1e6_rst;
  (* src = "tests2_feb2022/test1_amlib_timers.py:88" *)
  output ui__active;
  reg ui__active = 1'h0;
  (* src = "tests2_feb2022/test1_amlib_timers.py:96" *)
  reg \ui__active$3  = 1'h0;
  (* src = "tests2_feb2022/test1_amlib_timers.py:96" *)
  reg \ui__active$3$next ;
  (* src = "tests2_feb2022/test1_amlib_timers.py:88" *)
  reg \ui__active$next ;
  (* src = "tests2_feb2022/test1_amlib_timers.py:88" *)
  output ui__done;
  reg ui__done = 1'h0;
  (* src = "tests2_feb2022/test1_amlib_timers.py:96" *)
  reg \ui__done$2  = 1'h0;
  (* src = "tests2_feb2022/test1_amlib_timers.py:96" *)
  reg \ui__done$2$next ;
  (* src = "tests2_feb2022/test1_amlib_timers.py:88" *)
  reg \ui__done$next ;
  (* src = "tests2_feb2022/test1_amlib_timers.py:88" *)
  input ui__start;
  (* src = "tests2_feb2022/test1_amlib_timers.py:96" *)
  reg \ui__start$1  = 1'h0;
  (* src = "tests2_feb2022/test1_amlib_timers.py:96" *)
  reg \ui__start$1$next ;
  always @(posedge sync_1e6_clk)
    leds <= debug__count[22:15];
  always @(posedge sync_1e6_clk)
    debug__count <= \debug__count$next ;
  always @(posedge sync_1e6_clk)
    \ui__active$3  <= \ui__active$3$next ;
  always @(posedge sync_1e6_clk)
    \ui__done$2  <= \ui__done$2$next ;
  always @(posedge sync_1e6_clk)
    dut_ui__start <= \dut_ui__start$next ;
  always @(posedge sync_1e6_clk)
    ui__active <= \ui__active$next ;
  always @(posedge sync_1e6_clk)
    ui__done <= \ui__done$next ;
  always @(posedge sync_1e6_clk)
    \ui__start$1  <= \ui__start$1$next ;
  dut dut (
    .debug__count(dut_debug__count),
    .sync_1e6_clk(sync_1e6_clk),
    .sync_1e6_rst(sync_1e6_rst),
    .ui__active(dut_ui__active),
    .ui__done(dut_ui__done),
    .ui__start(dut_ui__start)
  );
  always @* begin
    if (\$auto$verilog_backend.cc:2083:dump_module$51 ) begin end
    \ui__start$1$next  = ui__start;
    (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/xfrm.py:519" *)
    casez (sync_1e6_rst)
      1'h1:
          \ui__start$1$next  = 1'h0;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2083:dump_module$51 ) begin end
    \ui__done$next  = \ui__done$2 ;
    (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/xfrm.py:519" *)
    casez (sync_1e6_rst)
      1'h1:
          \ui__done$next  = 1'h0;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2083:dump_module$51 ) begin end
    \ui__active$next  = \ui__active$3 ;
    (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/xfrm.py:519" *)
    casez (sync_1e6_rst)
      1'h1:
          \ui__active$next  = 1'h0;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2083:dump_module$51 ) begin end
    \dut_ui__start$next  = \ui__start$1 ;
    (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/xfrm.py:519" *)
    casez (sync_1e6_rst)
      1'h1:
          \dut_ui__start$next  = 1'h0;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2083:dump_module$51 ) begin end
    \ui__done$2$next  = dut_ui__done;
    (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/xfrm.py:519" *)
    casez (sync_1e6_rst)
      1'h1:
          \ui__done$2$next  = 1'h0;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2083:dump_module$51 ) begin end
    \ui__active$3$next  = dut_ui__active;
    (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/xfrm.py:519" *)
    casez (sync_1e6_rst)
      1'h1:
          \ui__active$3$next  = 1'h0;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2083:dump_module$51 ) begin end
    \debug__count$next  = dut_debug__count;
    (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/xfrm.py:519" *)
    casez (sync_1e6_rst)
      1'h1:
          \debug__count$next  = 32'd0;
    endcase
  end
  assign \leds$next  = debug__count[22:15];
endmodule

(* \amaranth.hierarchy  = "top" *)
(* top =  1  *)
(* generator = "Amaranth" *)
module top(led_0__io, led_1__io, led_2__io, led_3__io, led_4__io, led_5__io, led_6__io, led_7__io, esp32_spi_0__en__io, esp32_spi_0__tx__io, esp32_spi_0__rx__io, esp32_spi_0__gpio4_copi__io, esp32_spi_0__gpio5_cs__io, esp32_spi_0__gpio12_cipo__io, esp32_spi_0__gpio16_sclk__io, uart_0__rx__io, uart_0__tx__io, uart_0__rts__io, uart_0__dtr__io, clk25_0__io, button_pwr_0__io
, button_fire_0__io, button_fire_1__io, button_up_0__io, button_down_0__io, button_left_0__io, button_right_0__io, esp32_spi_0__gpio0__io);
  reg \$auto$verilog_backend.cc:2083:dump_module$52  = 0;
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/gateware/amtest/amtest/boards/ulx3s/common/clks.py:32" *)
  wire [4:0] \$1 ;
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/gateware/amtest/amtest/boards/ulx3s/common/clks.py:33" *)
  wire \$10 ;
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/gateware/amtest/amtest/boards/ulx3s/common/clks.py:33" *)
  wire \$11 ;
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/gateware/amtest/amtest/boards/ulx3s/common/upload.py:113" *)
  wire \$14 ;
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/gateware/amtest/amtest/boards/ulx3s/common/upload.py:113" *)
  wire \$16 ;
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/gateware/amtest/amtest/boards/ulx3s/common/upload.py:113" *)
  wire \$18 ;
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/gateware/amtest/amtest/boards/ulx3s/common/clks.py:32" *)
  wire [4:0] \$2 ;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/rec.py:258" *)
  wire \$20 ;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/rec.py:258" *)
  wire \$22 ;
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/gateware/amtest/amtest/boards/ulx3s/common/upload.py:116" *)
  wire \$24 ;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/rec.py:258" *)
  wire \$26 ;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/rec.py:258" *)
  wire \$28 ;
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/gateware/amtest/amtest/boards/ulx3s/common/upload.py:119" *)
  wire \$30 ;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/rec.py:258" *)
  wire \$32 ;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/rec.py:258" *)
  wire \$34 ;
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/gateware/amtest/amtest/boards/ulx3s/common/upload.py:122" *)
  wire \$36 ;
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/gateware/amtest/amtest/boards/ulx3s/common/upload.py:114" *)
  wire \$38 ;
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/gateware/amtest/amtest/boards/ulx3s/common/clks.py:32" *)
  wire [4:0] \$4 ;
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/gateware/amtest/amtest/boards/ulx3s/common/upload.py:114" *)
  wire \$40 ;
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/gateware/amtest/amtest/boards/ulx3s/common/upload.py:117" *)
  wire \$42 ;
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/gateware/amtest/amtest/boards/ulx3s/common/upload.py:117" *)
  wire \$44 ;
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/gateware/amtest/amtest/boards/ulx3s/common/upload.py:120" *)
  wire \$46 ;
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/gateware/amtest/amtest/boards/ulx3s/common/upload.py:120" *)
  wire \$48 ;
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/gateware/amtest/amtest/boards/ulx3s/common/clks.py:32" *)
  wire \$5 ;
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/gateware/amtest/amtest/boards/ulx3s/common/upload.py:123" *)
  wire \$50 ;
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/gateware/amtest/amtest/boards/ulx3s/common/upload.py:123" *)
  wire \$52 ;
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/gateware/amtest/amtest/boards/ulx3s/common/upload.py:113" *)
  wire \$54 ;
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/gateware/amtest/amtest/boards/ulx3s/common/upload.py:113" *)
  wire \$56 ;
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/gateware/amtest/amtest/boards/ulx3s/common/upload.py:113" *)
  wire \$58 ;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/rec.py:258" *)
  wire \$60 ;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/rec.py:258" *)
  wire \$62 ;
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/gateware/amtest/amtest/boards/ulx3s/common/upload.py:116" *)
  wire \$64 ;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/rec.py:258" *)
  wire \$66 ;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/rec.py:258" *)
  wire \$68 ;
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/gateware/amtest/amtest/boards/ulx3s/common/upload.py:119" *)
  wire \$70 ;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/rec.py:258" *)
  wire \$72 ;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/rec.py:258" *)
  wire \$74 ;
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/gateware/amtest/amtest/boards/ulx3s/common/upload.py:122" *)
  wire \$76 ;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/ast.py:1369" *)
  wire \$78 ;
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/gateware/amtest/amtest/boards/ulx3s/common/clks.py:33" *)
  wire \$8 ;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/ast.py:1369" *)
  wire \$80 ;
  (* \amaranth.sample_reg  = 32'd1 *)
  (* src = "tests2_feb2022/test1_amlib_timers.py:260" *)
  reg \$sample$s$start$sync_1e6$1  = 1'h0;
  (* src = "tests2_feb2022/test1_amlib_timers.py:260" *)
  wire \$sample$s$start$sync_1e6$1$next ;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  input button_down_0__io;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  input button_fire_0__io;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  input button_fire_1__io;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  input button_left_0__io;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  input button_pwr_0__io;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  input button_right_0__io;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  input button_up_0__io;
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/gateware/amtest/amtest/boards/ulx3s/common/clks.py:40" *)
  wire clk;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  input clk25_0__io;
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/gateware/amtest/amtest/boards/ulx3s/common/clks.py:30" *)
  reg [3:0] clk_counter = 4'h0;
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/gateware/amtest/amtest/boards/ulx3s/common/clks.py:30" *)
  reg [3:0] \clk_counter$next ;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  output esp32_spi_0__en__io;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  inout esp32_spi_0__gpio0__io;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  output esp32_spi_0__gpio12_cipo__io;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  input esp32_spi_0__gpio16_sclk__io;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  input esp32_spi_0__gpio4_copi__io;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  input esp32_spi_0__gpio5_cs__io;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  input esp32_spi_0__rx__io;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  output esp32_spi_0__tx__io;
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/gateware/amtest/amtest/boards/ulx3s/common/upload.py:85" *)
  wire i_button_ffsync_i_buttons__left;
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/gateware/amtest/amtest/boards/ulx3s/common/upload.py:85" *)
  wire i_button_ffsync_i_buttons__pwr;
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/gateware/amtest/amtest/boards/ulx3s/common/upload.py:85" *)
  wire i_button_ffsync_i_buttons__right;
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/gateware/amtest/amtest/boards/ulx3s/common/upload.py:61" *)
  reg i_button_ffsync_i_unsync_buttons__down = 1'h0;
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/gateware/amtest/amtest/boards/ulx3s/common/upload.py:61" *)
  reg \i_button_ffsync_i_unsync_buttons__down$next ;
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/gateware/amtest/amtest/boards/ulx3s/common/upload.py:61" *)
  reg i_button_ffsync_i_unsync_buttons__fireA = 1'h0;
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/gateware/amtest/amtest/boards/ulx3s/common/upload.py:61" *)
  reg \i_button_ffsync_i_unsync_buttons__fireA$next ;
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/gateware/amtest/amtest/boards/ulx3s/common/upload.py:61" *)
  reg i_button_ffsync_i_unsync_buttons__fireB = 1'h0;
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/gateware/amtest/amtest/boards/ulx3s/common/upload.py:61" *)
  reg \i_button_ffsync_i_unsync_buttons__fireB$next ;
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/gateware/amtest/amtest/boards/ulx3s/common/upload.py:61" *)
  reg i_button_ffsync_i_unsync_buttons__left = 1'h0;
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/gateware/amtest/amtest/boards/ulx3s/common/upload.py:61" *)
  reg \i_button_ffsync_i_unsync_buttons__left$next ;
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/gateware/amtest/amtest/boards/ulx3s/common/upload.py:61" *)
  reg i_button_ffsync_i_unsync_buttons__pwr = 1'h0;
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/gateware/amtest/amtest/boards/ulx3s/common/upload.py:61" *)
  reg \i_button_ffsync_i_unsync_buttons__pwr$next ;
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/gateware/amtest/amtest/boards/ulx3s/common/upload.py:61" *)
  reg i_button_ffsync_i_unsync_buttons__right = 1'h0;
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/gateware/amtest/amtest/boards/ulx3s/common/upload.py:61" *)
  reg \i_button_ffsync_i_unsync_buttons__right$next ;
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/gateware/amtest/amtest/boards/ulx3s/common/upload.py:61" *)
  reg i_button_ffsync_i_unsync_buttons__up = 1'h0;
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/gateware/amtest/amtest/boards/ulx3s/common/upload.py:61" *)
  reg \i_button_ffsync_i_unsync_buttons__up$next ;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  output led_0__io;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  output led_1__io;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  output led_2__io;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  output led_3__io;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  output led_4__io;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  output led_5__io;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  output led_6__io;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  output led_7__io;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  wire pin_button_down_0_button_down_0__i;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  wire pin_button_fire_0_button_fire_0__i;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  wire pin_button_fire_1_button_fire_1__i;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  wire pin_button_left_0_button_left_0__i;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  wire pin_button_pwr_0_button_pwr_0__i;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  wire pin_button_right_0_button_right_0__i;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  wire pin_button_up_0_button_up_0__i;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  wire pin_clk25_0_clk25_0__i;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  reg pin_esp32_spi_0__en_esp32_spi_0__en__o = 1'h0;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  reg \pin_esp32_spi_0__en_esp32_spi_0__en__o$next ;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  reg pin_esp32_spi_0__gpio0_esp32_spi_0__gpio0__o = 1'h0;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  reg \pin_esp32_spi_0__gpio0_esp32_spi_0__gpio0__o$next ;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  wire pin_esp32_spi_0__rx_esp32_spi_0__rx__i;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  reg pin_esp32_spi_0__tx_esp32_spi_0__tx__o = 1'h0;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  reg \pin_esp32_spi_0__tx_esp32_spi_0__tx__o$next ;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  reg pin_led_0_led_0__o = 1'h0;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  reg \pin_led_0_led_0__o$next ;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  reg pin_led_1_led_1__o = 1'h0;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  reg \pin_led_1_led_1__o$next ;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  reg pin_led_2_led_2__o = 1'h0;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  reg \pin_led_2_led_2__o$next ;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  reg pin_led_3_led_3__o = 1'h0;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  reg \pin_led_3_led_3__o$next ;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  reg pin_led_4_led_4__o = 1'h0;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  reg \pin_led_4_led_4__o$next ;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  reg pin_led_5_led_5__o = 1'h0;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  reg \pin_led_5_led_5__o$next ;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  reg pin_led_6_led_6__o = 1'h0;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  reg \pin_led_6_led_6__o$next ;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  reg pin_led_7_led_7__o = 1'h0;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  reg \pin_led_7_led_7__o$next ;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  wire pin_uart_0__dtr_uart_0__dtr__i;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  wire pin_uart_0__rts_uart_0__rts__i;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  wire pin_uart_0__rx_uart_0__rx__i;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  reg pin_uart_0__tx_uart_0__tx__o = 1'h0;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  reg \pin_uart_0__tx_uart_0__tx__o$next ;
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/gateware/amtest/amtest/boards/ulx3s/common/clks.py:40" *)
  wire rst;
  (* src = "tests2_feb2022/test1_amlib_timers.py:260" *)
  reg start = 1'h0;
  (* src = "tests2_feb2022/test1_amlib_timers.py:260" *)
  reg \start$next ;
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/gateware/amtest/amtest/boards/ulx3s/common/clks.py:26" *)
  reg sync_1e6_clk = 1'h0;
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/gateware/amtest/amtest/boards/ulx3s/common/clks.py:26" *)
  reg \sync_1e6_clk$next ;
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/gateware/amtest/amtest/boards/ulx3s/common/clks.py:26" *)
  reg sync_1e6_rst = 1'h0;
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/gateware/amtest/amtest/boards/ulx3s/common/clks.py:26" *)
  reg \sync_1e6_rst$next ;
  (* src = "tests2_feb2022/test1_amlib_timers.py:89" *)
  wire [7:0] tb_leds;
  (* src = "tests2_feb2022/test1_amlib_timers.py:88" *)
  wire tb_ui__active;
  (* src = "tests2_feb2022/test1_amlib_timers.py:88" *)
  wire tb_ui__done;
  (* src = "tests2_feb2022/test1_amlib_timers.py:88" *)
  reg tb_ui__start = 1'h0;
  (* src = "tests2_feb2022/test1_amlib_timers.py:88" *)
  reg \tb_ui__start$next ;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  input uart_0__dtr__io;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  input uart_0__rts__io;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  input uart_0__rx__io;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  output uart_0__tx__io;
  (* src = "tests2_feb2022/test1_amlib_timers.py:248" *)
  reg ui__active = 1'h0;
  (* src = "tests2_feb2022/test1_amlib_timers.py:248" *)
  reg \ui__active$next ;
  (* src = "tests2_feb2022/test1_amlib_timers.py:248" *)
  reg ui__done = 1'h0;
  (* src = "tests2_feb2022/test1_amlib_timers.py:248" *)
  reg \ui__done$next ;
  (* src = "tests2_feb2022/test1_amlib_timers.py:248" *)
  reg ui__start = 1'h0;
  (* src = "tests2_feb2022/test1_amlib_timers.py:248" *)
  reg \ui__start$next ;
  assign \$11  = ! (* src = "/home/ubuntu/from_host/x/Documents/git_repos/gateware/amtest/amtest/boards/ulx3s/common/clks.py:33" *) clk_counter;
  assign \$10  = \$11  ? (* src = "/home/ubuntu/from_host/x/Documents/git_repos/gateware/amtest/amtest/boards/ulx3s/common/clks.py:33" *) \$8  : sync_1e6_clk;
  assign \$18  = \$14  & (* src = "/home/ubuntu/from_host/x/Documents/git_repos/gateware/amtest/amtest/boards/ulx3s/common/upload.py:113" *) \$16 ;
  assign \$20  = ~ (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/rec.py:258" *) pin_uart_0__dtr_uart_0__dtr__i;
  assign \$22  = ~ (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/rec.py:258" *) pin_uart_0__rts_uart_0__rts__i;
  assign \$24  = \$20  & (* src = "/home/ubuntu/from_host/x/Documents/git_repos/gateware/amtest/amtest/boards/ulx3s/common/upload.py:116" *) \$22 ;
  assign \$28  = ~ (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/rec.py:258" *) pin_uart_0__rts_uart_0__rts__i;
  assign \$2  = clk_counter + (* src = "/home/ubuntu/from_host/x/Documents/git_repos/gateware/amtest/amtest/boards/ulx3s/common/clks.py:32" *) 1'h1;
  assign \$30  = \$26  & (* src = "/home/ubuntu/from_host/x/Documents/git_repos/gateware/amtest/amtest/boards/ulx3s/common/upload.py:119" *) \$28 ;
  assign \$32  = ~ (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/rec.py:258" *) pin_uart_0__dtr_uart_0__dtr__i;
  assign \$36  = \$32  & (* src = "/home/ubuntu/from_host/x/Documents/git_repos/gateware/amtest/amtest/boards/ulx3s/common/upload.py:122" *) \$34 ;
  assign \$38  = ~ (* src = "/home/ubuntu/from_host/x/Documents/git_repos/gateware/amtest/amtest/boards/ulx3s/common/upload.py:114" *) i_button_ffsync_i_buttons__pwr;
  assign \$42  = ~ (* src = "/home/ubuntu/from_host/x/Documents/git_repos/gateware/amtest/amtest/boards/ulx3s/common/upload.py:117" *) i_button_ffsync_i_buttons__pwr;
  assign \$46  = ~ (* src = "/home/ubuntu/from_host/x/Documents/git_repos/gateware/amtest/amtest/boards/ulx3s/common/upload.py:120" *) i_button_ffsync_i_buttons__pwr;
  assign \$50  = ~ (* src = "/home/ubuntu/from_host/x/Documents/git_repos/gateware/amtest/amtest/boards/ulx3s/common/upload.py:123" *) i_button_ffsync_i_buttons__pwr;
  assign \$58  = \$54  & (* src = "/home/ubuntu/from_host/x/Documents/git_repos/gateware/amtest/amtest/boards/ulx3s/common/upload.py:113" *) \$56 ;
  assign \$5  = clk_counter == (* src = "/home/ubuntu/from_host/x/Documents/git_repos/gateware/amtest/amtest/boards/ulx3s/common/clks.py:32" *) 4'hb;
  assign \$60  = ~ (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/rec.py:258" *) pin_uart_0__dtr_uart_0__dtr__i;
  assign \$62  = ~ (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/rec.py:258" *) pin_uart_0__rts_uart_0__rts__i;
  assign \$64  = \$60  & (* src = "/home/ubuntu/from_host/x/Documents/git_repos/gateware/amtest/amtest/boards/ulx3s/common/upload.py:116" *) \$62 ;
  assign \$68  = ~ (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/rec.py:258" *) pin_uart_0__rts_uart_0__rts__i;
  assign \$4  = \$5  ? (* src = "/home/ubuntu/from_host/x/Documents/git_repos/gateware/amtest/amtest/boards/ulx3s/common/clks.py:32" *) 5'h00 : \$2 ;
  assign \$70  = \$66  & (* src = "/home/ubuntu/from_host/x/Documents/git_repos/gateware/amtest/amtest/boards/ulx3s/common/upload.py:119" *) \$68 ;
  assign \$72  = ~ (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/rec.py:258" *) pin_uart_0__dtr_uart_0__dtr__i;
  assign \$76  = \$72  & (* src = "/home/ubuntu/from_host/x/Documents/git_repos/gateware/amtest/amtest/boards/ulx3s/common/upload.py:122" *) \$74 ;
  assign \$78  = ~ (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/ast.py:1369" *) \$sample$s$start$sync_1e6$1 ;
  assign \$80  = \$78  & (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/ast.py:1369" *) start;
  assign \$8  = ~ (* src = "/home/ubuntu/from_host/x/Documents/git_repos/gateware/amtest/amtest/boards/ulx3s/common/clks.py:33" *) sync_1e6_clk;
  always @(posedge sync_1e6_clk)
    \$sample$s$start$sync_1e6$1  <= start;
  always @(posedge sync_1e6_clk)
    ui__start <= \ui__start$next ;
  always @(posedge sync_1e6_clk)
    start <= \start$next ;
  always @(posedge sync_1e6_clk)
    sync_1e6_rst <= \sync_1e6_rst$next ;
  always @(posedge sync_1e6_clk)
    ui__active <= \ui__active$next ;
  always @(posedge sync_1e6_clk)
    ui__done <= \ui__done$next ;
  always @(posedge sync_1e6_clk)
    tb_ui__start <= \tb_ui__start$next ;
  always @(posedge clk)
    pin_esp32_spi_0__gpio0_esp32_spi_0__gpio0__o <= \pin_esp32_spi_0__gpio0_esp32_spi_0__gpio0__o$next ;
  always @(posedge clk)
    pin_esp32_spi_0__en_esp32_spi_0__en__o <= \pin_esp32_spi_0__en_esp32_spi_0__en__o$next ;
  always @(posedge clk)
    pin_uart_0__tx_uart_0__tx__o <= \pin_uart_0__tx_uart_0__tx__o$next ;
  always @(posedge clk)
    pin_esp32_spi_0__tx_esp32_spi_0__tx__o <= \pin_esp32_spi_0__tx_esp32_spi_0__tx__o$next ;
  always @(posedge sync_1e6_clk)
    pin_led_0_led_0__o <= \pin_led_0_led_0__o$next ;
  always @(posedge sync_1e6_clk)
    i_button_ffsync_i_unsync_buttons__right <= \i_button_ffsync_i_unsync_buttons__right$next ;
  always @(posedge sync_1e6_clk)
    i_button_ffsync_i_unsync_buttons__left <= \i_button_ffsync_i_unsync_buttons__left$next ;
  always @(posedge sync_1e6_clk)
    i_button_ffsync_i_unsync_buttons__down <= \i_button_ffsync_i_unsync_buttons__down$next ;
  always @(posedge sync_1e6_clk)
    i_button_ffsync_i_unsync_buttons__up <= \i_button_ffsync_i_unsync_buttons__up$next ;
  always @(posedge sync_1e6_clk)
    i_button_ffsync_i_unsync_buttons__fireB <= \i_button_ffsync_i_unsync_buttons__fireB$next ;
  always @(posedge sync_1e6_clk)
    i_button_ffsync_i_unsync_buttons__fireA <= \i_button_ffsync_i_unsync_buttons__fireA$next ;
  always @(posedge sync_1e6_clk)
    i_button_ffsync_i_unsync_buttons__pwr <= \i_button_ffsync_i_unsync_buttons__pwr$next ;
  always @(posedge clk)
    sync_1e6_clk <= \sync_1e6_clk$next ;
  always @(posedge clk)
    clk_counter <= \clk_counter$next ;
  always @(posedge sync_1e6_clk)
    pin_led_1_led_1__o <= \pin_led_1_led_1__o$next ;
  always @(posedge sync_1e6_clk)
    pin_led_2_led_2__o <= \pin_led_2_led_2__o$next ;
  always @(posedge sync_1e6_clk)
    pin_led_3_led_3__o <= \pin_led_3_led_3__o$next ;
  always @(posedge sync_1e6_clk)
    pin_led_4_led_4__o <= \pin_led_4_led_4__o$next ;
  always @(posedge sync_1e6_clk)
    pin_led_5_led_5__o <= \pin_led_5_led_5__o$next ;
  always @(posedge sync_1e6_clk)
    pin_led_6_led_6__o <= \pin_led_6_led_6__o$next ;
  always @(posedge sync_1e6_clk)
    pin_led_7_led_7__o <= \pin_led_7_led_7__o$next ;
  i_button_ffsync i_button_ffsync (
    .clk(clk),
    .i_buttons__left(i_button_ffsync_i_buttons__left),
    .i_buttons__pwr(i_button_ffsync_i_buttons__pwr),
    .i_buttons__right(i_button_ffsync_i_buttons__right),
    .i_unsync_buttons__down(i_button_ffsync_i_unsync_buttons__down),
    .i_unsync_buttons__fireA(i_button_ffsync_i_unsync_buttons__fireA),
    .i_unsync_buttons__fireB(i_button_ffsync_i_unsync_buttons__fireB),
    .i_unsync_buttons__left(i_button_ffsync_i_unsync_buttons__left),
    .i_unsync_buttons__pwr(i_button_ffsync_i_unsync_buttons__pwr),
    .i_unsync_buttons__right(i_button_ffsync_i_unsync_buttons__right),
    .i_unsync_buttons__up(i_button_ffsync_i_unsync_buttons__up),
    .rst(1'h0)
  );
  pin_button_down_0 pin_button_down_0 (
    .button_down_0__i(pin_button_down_0_button_down_0__i),
    .button_down_0__io(button_down_0__io)
  );
  pin_button_fire_0 pin_button_fire_0 (
    .button_fire_0__i(pin_button_fire_0_button_fire_0__i),
    .button_fire_0__io(button_fire_0__io)
  );
  pin_button_fire_1 pin_button_fire_1 (
    .button_fire_1__i(pin_button_fire_1_button_fire_1__i),
    .button_fire_1__io(button_fire_1__io)
  );
  pin_button_left_0 pin_button_left_0 (
    .button_left_0__i(pin_button_left_0_button_left_0__i),
    .button_left_0__io(button_left_0__io)
  );
  pin_button_pwr_0 pin_button_pwr_0 (
    .button_pwr_0__i(pin_button_pwr_0_button_pwr_0__i),
    .button_pwr_0__io(button_pwr_0__io)
  );
  pin_button_right_0 pin_button_right_0 (
    .button_right_0__i(pin_button_right_0_button_right_0__i),
    .button_right_0__io(button_right_0__io)
  );
  pin_button_up_0 pin_button_up_0 (
    .button_up_0__i(pin_button_up_0_button_up_0__i),
    .button_up_0__io(button_up_0__io)
  );
  pin_clk25_0 pin_clk25_0 (
    .clk25_0__i(pin_clk25_0_clk25_0__i),
    .clk25_0__io(clk25_0__io)
  );
  pin_esp32_spi_0__en pin_esp32_spi_0__en (
    .esp32_spi_0__en__io(esp32_spi_0__en__io),
    .esp32_spi_0__en__o(pin_esp32_spi_0__en_esp32_spi_0__en__o)
  );
  pin_esp32_spi_0__gpio0 pin_esp32_spi_0__gpio0 (
    .esp32_spi_0__gpio0__io(esp32_spi_0__gpio0__io),
    .esp32_spi_0__gpio0__o(pin_esp32_spi_0__gpio0_esp32_spi_0__gpio0__o)
  );
  pin_esp32_spi_0__gpio12_cipo pin_esp32_spi_0__gpio12_cipo (
    .esp32_spi_0__gpio12_cipo__io(esp32_spi_0__gpio12_cipo__io)
  );
  pin_esp32_spi_0__gpio16_sclk pin_esp32_spi_0__gpio16_sclk (
    .esp32_spi_0__gpio16_sclk__io(esp32_spi_0__gpio16_sclk__io)
  );
  pin_esp32_spi_0__gpio4_copi pin_esp32_spi_0__gpio4_copi (
    .esp32_spi_0__gpio4_copi__io(esp32_spi_0__gpio4_copi__io)
  );
  pin_esp32_spi_0__gpio5_cs pin_esp32_spi_0__gpio5_cs (
    .esp32_spi_0__gpio5_cs__io(esp32_spi_0__gpio5_cs__io)
  );
  pin_esp32_spi_0__rx pin_esp32_spi_0__rx (
    .esp32_spi_0__rx__i(pin_esp32_spi_0__rx_esp32_spi_0__rx__i),
    .esp32_spi_0__rx__io(esp32_spi_0__rx__io)
  );
  pin_esp32_spi_0__tx pin_esp32_spi_0__tx (
    .esp32_spi_0__tx__io(esp32_spi_0__tx__io),
    .esp32_spi_0__tx__o(pin_esp32_spi_0__tx_esp32_spi_0__tx__o)
  );
  pin_led_0 pin_led_0 (
    .led_0__io(led_0__io),
    .led_0__o(pin_led_0_led_0__o)
  );
  pin_led_1 pin_led_1 (
    .led_1__io(led_1__io),
    .led_1__o(pin_led_1_led_1__o)
  );
  pin_led_2 pin_led_2 (
    .led_2__io(led_2__io),
    .led_2__o(pin_led_2_led_2__o)
  );
  pin_led_3 pin_led_3 (
    .led_3__io(led_3__io),
    .led_3__o(pin_led_3_led_3__o)
  );
  pin_led_4 pin_led_4 (
    .led_4__io(led_4__io),
    .led_4__o(pin_led_4_led_4__o)
  );
  pin_led_5 pin_led_5 (
    .led_5__io(led_5__io),
    .led_5__o(pin_led_5_led_5__o)
  );
  pin_led_6 pin_led_6 (
    .led_6__io(led_6__io),
    .led_6__o(pin_led_6_led_6__o)
  );
  pin_led_7 pin_led_7 (
    .led_7__io(led_7__io),
    .led_7__o(pin_led_7_led_7__o)
  );
  pin_uart_0__dtr pin_uart_0__dtr (
    .uart_0__dtr__i(pin_uart_0__dtr_uart_0__dtr__i),
    .uart_0__dtr__io(uart_0__dtr__io)
  );
  pin_uart_0__rts pin_uart_0__rts (
    .uart_0__rts__i(pin_uart_0__rts_uart_0__rts__i),
    .uart_0__rts__io(uart_0__rts__io)
  );
  pin_uart_0__rx pin_uart_0__rx (
    .uart_0__rx__i(pin_uart_0__rx_uart_0__rx__i),
    .uart_0__rx__io(uart_0__rx__io)
  );
  pin_uart_0__tx pin_uart_0__tx (
    .uart_0__tx__io(uart_0__tx__io),
    .uart_0__tx__o(pin_uart_0__tx_uart_0__tx__o)
  );
  tb tb (
    .leds(tb_leds),
    .sync_1e6_clk(sync_1e6_clk),
    .sync_1e6_rst(sync_1e6_rst),
    .ui__active(tb_ui__active),
    .ui__done(tb_ui__done),
    .ui__start(tb_ui__start)
  );
  always @* begin
    if (\$auto$verilog_backend.cc:2083:dump_module$52 ) begin end
    \clk_counter$next  = \$4 [3:0];
    (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \clk_counter$next  = 4'h0;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2083:dump_module$52 ) begin end
    \pin_esp32_spi_0__tx_esp32_spi_0__tx__o$next  = pin_uart_0__rx_uart_0__rx__i;
    (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \pin_esp32_spi_0__tx_esp32_spi_0__tx__o$next  = 1'h0;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2083:dump_module$52 ) begin end
    \pin_uart_0__tx_uart_0__tx__o$next  = pin_esp32_spi_0__rx_esp32_spi_0__rx__i;
    (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \pin_uart_0__tx_uart_0__tx__o$next  = 1'h0;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2083:dump_module$52 ) begin end
    \pin_esp32_spi_0__en_esp32_spi_0__en__o$next  = pin_esp32_spi_0__en_esp32_spi_0__en__o;
    (* src = "/home/ubuntu/from_host/x/Documents/git_repos/gateware/amtest/amtest/boards/ulx3s/common/upload.py:113" *)
    casez ({ \$36 , \$30 , \$24 , \$18  })
      /* src = "/home/ubuntu/from_host/x/Documents/git_repos/gateware/amtest/amtest/boards/ulx3s/common/upload.py:113" */
      4'b???1:
          \pin_esp32_spi_0__en_esp32_spi_0__en__o$next  = \$40 ;
      /* src = "/home/ubuntu/from_host/x/Documents/git_repos/gateware/amtest/amtest/boards/ulx3s/common/upload.py:116" */
      4'b??1?:
          \pin_esp32_spi_0__en_esp32_spi_0__en__o$next  = \$44 ;
      /* src = "/home/ubuntu/from_host/x/Documents/git_repos/gateware/amtest/amtest/boards/ulx3s/common/upload.py:119" */
      4'b?1??:
          \pin_esp32_spi_0__en_esp32_spi_0__en__o$next  = \$48 ;
      /* src = "/home/ubuntu/from_host/x/Documents/git_repos/gateware/amtest/amtest/boards/ulx3s/common/upload.py:122" */
      4'b1???:
          \pin_esp32_spi_0__en_esp32_spi_0__en__o$next  = \$52 ;
    endcase
    (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \pin_esp32_spi_0__en_esp32_spi_0__en__o$next  = 1'h0;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2083:dump_module$52 ) begin end
    \pin_esp32_spi_0__gpio0_esp32_spi_0__gpio0__o$next  = pin_esp32_spi_0__gpio0_esp32_spi_0__gpio0__o;
    (* src = "/home/ubuntu/from_host/x/Documents/git_repos/gateware/amtest/amtest/boards/ulx3s/common/upload.py:113" *)
    casez ({ \$76 , \$70 , \$64 , \$58  })
      /* src = "/home/ubuntu/from_host/x/Documents/git_repos/gateware/amtest/amtest/boards/ulx3s/common/upload.py:113" */
      4'b???1:
          \pin_esp32_spi_0__gpio0_esp32_spi_0__gpio0__o$next  = 1'h1;
      /* src = "/home/ubuntu/from_host/x/Documents/git_repos/gateware/amtest/amtest/boards/ulx3s/common/upload.py:116" */
      4'b??1?:
          \pin_esp32_spi_0__gpio0_esp32_spi_0__gpio0__o$next  = 1'h1;
      /* src = "/home/ubuntu/from_host/x/Documents/git_repos/gateware/amtest/amtest/boards/ulx3s/common/upload.py:119" */
      4'b?1??:
          \pin_esp32_spi_0__gpio0_esp32_spi_0__gpio0__o$next  = 1'h1;
      /* src = "/home/ubuntu/from_host/x/Documents/git_repos/gateware/amtest/amtest/boards/ulx3s/common/upload.py:122" */
      4'b1???:
          \pin_esp32_spi_0__gpio0_esp32_spi_0__gpio0__o$next  = 1'h0;
    endcase
    (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \pin_esp32_spi_0__gpio0_esp32_spi_0__gpio0__o$next  = 1'h0;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2083:dump_module$52 ) begin end
    \tb_ui__start$next  = ui__start;
    (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/xfrm.py:519" *)
    casez (sync_1e6_rst)
      1'h1:
          \tb_ui__start$next  = 1'h0;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2083:dump_module$52 ) begin end
    \ui__done$next  = tb_ui__done;
    (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/xfrm.py:519" *)
    casez (sync_1e6_rst)
      1'h1:
          \ui__done$next  = 1'h0;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2083:dump_module$52 ) begin end
    \ui__active$next  = tb_ui__active;
    (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/xfrm.py:519" *)
    casez (sync_1e6_rst)
      1'h1:
          \ui__active$next  = 1'h0;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2083:dump_module$52 ) begin end
    \sync_1e6_rst$next  = i_button_ffsync_i_buttons__right;
    (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/xfrm.py:519" *)
    casez (sync_1e6_rst)
      1'h1:
          \sync_1e6_rst$next  = 1'h0;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2083:dump_module$52 ) begin end
    \start$next  = i_button_ffsync_i_buttons__left;
    (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/xfrm.py:519" *)
    casez (sync_1e6_rst)
      1'h1:
          \start$next  = 1'h0;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2083:dump_module$52 ) begin end
    \ui__start$next  = \$80 ;
    (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/xfrm.py:519" *)
    casez (sync_1e6_rst)
      1'h1:
          \ui__start$next  = 1'h0;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2083:dump_module$52 ) begin end
    \sync_1e6_clk$next  = \$10 ;
    (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \sync_1e6_clk$next  = 1'h0;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2083:dump_module$52 ) begin end
    { \pin_led_7_led_7__o$next , \pin_led_6_led_6__o$next , \pin_led_5_led_5__o$next , \pin_led_4_led_4__o$next , \pin_led_3_led_3__o$next , \pin_led_2_led_2__o$next , \pin_led_1_led_1__o$next , \pin_led_0_led_0__o$next  } = tb_leds;
    (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/xfrm.py:519" *)
    casez (sync_1e6_rst)
      1'h1:
        begin
          \pin_led_0_led_0__o$next  = 1'h0;
          \pin_led_1_led_1__o$next  = 1'h0;
          \pin_led_2_led_2__o$next  = 1'h0;
          \pin_led_3_led_3__o$next  = 1'h0;
          \pin_led_4_led_4__o$next  = 1'h0;
          \pin_led_5_led_5__o$next  = 1'h0;
          \pin_led_6_led_6__o$next  = 1'h0;
          \pin_led_7_led_7__o$next  = 1'h0;
        end
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2083:dump_module$52 ) begin end
    \i_button_ffsync_i_unsync_buttons__pwr$next  = pin_button_pwr_0_button_pwr_0__i;
    (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/xfrm.py:519" *)
    casez (sync_1e6_rst)
      1'h1:
          \i_button_ffsync_i_unsync_buttons__pwr$next  = 1'h0;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2083:dump_module$52 ) begin end
    \i_button_ffsync_i_unsync_buttons__fireA$next  = pin_button_fire_0_button_fire_0__i;
    (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/xfrm.py:519" *)
    casez (sync_1e6_rst)
      1'h1:
          \i_button_ffsync_i_unsync_buttons__fireA$next  = 1'h0;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2083:dump_module$52 ) begin end
    \i_button_ffsync_i_unsync_buttons__fireB$next  = pin_button_fire_1_button_fire_1__i;
    (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/xfrm.py:519" *)
    casez (sync_1e6_rst)
      1'h1:
          \i_button_ffsync_i_unsync_buttons__fireB$next  = 1'h0;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2083:dump_module$52 ) begin end
    \i_button_ffsync_i_unsync_buttons__up$next  = pin_button_up_0_button_up_0__i;
    (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/xfrm.py:519" *)
    casez (sync_1e6_rst)
      1'h1:
          \i_button_ffsync_i_unsync_buttons__up$next  = 1'h0;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2083:dump_module$52 ) begin end
    \i_button_ffsync_i_unsync_buttons__down$next  = pin_button_down_0_button_down_0__i;
    (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/xfrm.py:519" *)
    casez (sync_1e6_rst)
      1'h1:
          \i_button_ffsync_i_unsync_buttons__down$next  = 1'h0;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2083:dump_module$52 ) begin end
    \i_button_ffsync_i_unsync_buttons__left$next  = pin_button_left_0_button_left_0__i;
    (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/xfrm.py:519" *)
    casez (sync_1e6_rst)
      1'h1:
          \i_button_ffsync_i_unsync_buttons__left$next  = 1'h0;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2083:dump_module$52 ) begin end
    \i_button_ffsync_i_unsync_buttons__right$next  = pin_button_right_0_button_right_0__i;
    (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/xfrm.py:519" *)
    casez (sync_1e6_rst)
      1'h1:
          \i_button_ffsync_i_unsync_buttons__right$next  = 1'h0;
    endcase
  end
  assign \$1  = \$4 ;
  assign rst = 1'h0;
  assign \$sample$s$start$sync_1e6$1$next  = start;
  assign clk = pin_clk25_0_clk25_0__i;
  assign \$16  = pin_uart_0__rts_uart_0__rts__i;
  assign \$14  = pin_uart_0__dtr_uart_0__dtr__i;
  assign \$26  = pin_uart_0__dtr_uart_0__dtr__i;
  assign \$34  = pin_uart_0__rts_uart_0__rts__i;
  assign \$40  = \$38 ;
  assign \$44  = \$42 ;
  assign \$48  = 1'h0;
  assign \$52  = \$50 ;
  assign \$54  = pin_uart_0__dtr_uart_0__dtr__i;
  assign \$56  = pin_uart_0__rts_uart_0__rts__i;
  assign \$66  = pin_uart_0__dtr_uart_0__dtr__i;
  assign \$74  = pin_uart_0__rts_uart_0__rts__i;
endmodule
